#!/bin/bash
set -e

if [ "${DEBUG}" = true ]; then
  set -x
fi

DEF_POSTGRESQL_HOST=
DEF_POSTGRESQL_USERNAME=template
DEF_POSTGRESQL_PASSWORD=""

POSTGRESQL_HOST=${POSTGRESQL_HOST:-$DEF_POSTGRESQL_HOST}
POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-$DEF_POSTGRESQL_USERNAME}
POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-$DEF_POSTGRESQL_PASSWORD}

exec /bin/echo "${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}" "$@"